apiVersion: v1
kind: Service
metadata:
  name: results-service
  labels:
    app: results-app
    name: demo-voting-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    name: results-app-pod
    app: demo-voting-app
