apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    app: voting-app
    name: voting-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      NodePort: 30004
  selector:
    name: voting-app-pod
    app: demo-voting-app
